// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Day4HomeworkRecap$Day4 = require("../src/Day4HomeworkRecap.bs.js");

Jest.describe("Simple test", (function (param) {
        return Jest.test("Add example", (function (param) {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
                    }));
      }));

Jest.describe("Response", (function (param) {
        Jest.test("Loading state should respond with 'Loading'", (function (param) {
                return Jest.Expect[/* toBe */2]("Loading", Jest.Expect[/* expect */0](Day4HomeworkRecap$Day4.response(/* Loading */0)));
              }));
        Jest.test("General success state", (function (param) {
                return Jest.Expect[/* toBe */2]("John", Jest.Expect[/* expect */0](Day4HomeworkRecap$Day4.response(/* Success */Block.__(1, [/* record */[
                                        /* name */"John",
                                        /* age */10
                                      ]]))));
              }));
        return Jest.test("Vladimir Novick success state", (function (param) {
                      return Jest.Expect[/* toBe */2]("Howdy Vladimir", Jest.Expect[/* expect */0](Day4HomeworkRecap$Day4.response(/* Success */Block.__(1, [/* record */[
                                              /* name */"Vladimir Novick",
                                              /* age */30
                                            ]]))));
                    }));
      }));

/*  Not a pure module */
