// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AppCss = require("./App.css");
var Button$ReactHooksTemplate = require("./Button.bs.js");

function str(prim) {
  return prim;
}

var styles = AppCss;

function handleClick(_event) {
  alert("clicked!");
  return /* () */0;
}

function App(Props) {
  var message = Props.message;
  return React.createElement("div", {
              className: styles.app,
              onClick: handleClick
            }, message, React.createElement("p", undefined, "This should be the secondary color"), React.createElement(Button$ReactHooksTemplate.make, {
                  children: "Sup",
                  color: /* Green */756711075,
                  size: /* Large */48800667
                }));
}

var make = App;

exports.str = str;
exports.styles = styles;
exports.handleClick = handleClick;
exports.make = make;
/* styles Not a pure module */
