// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Cx$ReactHooksTemplate = require("./Cx.bs.js");
var ButtonStyles$ReactHooksTemplate = require("./ButtonStyles.bs.js");

function styleOfColor(color) {
  if (color >= 756711075) {
    return (function (prim) {
        return prim.green;
      });
  } else {
    return (function (prim) {
        return prim.purple;
      });
  }
}

function styleOfSize(size) {
  if (size !== 311976103) {
    if (size >= 861718677) {
      return (function (prim) {
          return prim.medium;
        });
    } else {
      return (function (prim) {
          return prim.large;
        });
    }
  } else {
    return (function (prim) {
        return prim.small;
      });
  }
}

function Button(Props) {
  var children = Props.children;
  var match = Props.color;
  var color = match !== undefined ? match : /* Purple */639527516;
  var match$1 = Props.size;
  var size = match$1 !== undefined ? match$1 : /* Medium */861718677;
  return React.createElement("div", {
              className: Cx$ReactHooksTemplate.extractSingleStyle((function (prim) {
                      return prim.buttonContainer;
                    }), ButtonStyles$ReactHooksTemplate.externalStyles)
            }, React.createElement("button", {
                  className: Cx$ReactHooksTemplate.composeStyles(Cx$ReactHooksTemplate.extractStyles(/* :: */[
                            (function (prim) {
                                return prim.base;
                              }),
                            /* :: */[
                              styleOfColor(color),
                              /* :: */[
                                styleOfSize(size),
                                /* [] */0
                              ]
                            ]
                          ], ButtonStyles$ReactHooksTemplate.externalStyles))
                }, children));
}

var styles = ButtonStyles$ReactHooksTemplate.externalStyles;

var make = Button;

exports.styles = styles;
exports.styleOfColor = styleOfColor;
exports.styleOfSize = styleOfSize;
exports.make = make;
/* react Not a pure module */
