// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ButtonCss = require("./Button.css");

var externalStyles = ButtonCss;

exports.externalStyles = externalStyles;
/* externalStyles Not a pure module */
