// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var NoSuchStyle = Caml_exceptions.create("Cx-ReactHooksTemplate.NoSuchStyle");

function composeStyles(classes) {
  return $$Array.fold_left((function (acc, class_) {
                if (acc === "") {
                  return acc + class_;
                } else {
                  return acc + (" " + class_);
                }
              }), "", classes);
}

function extractNullableStyle(style) {
  if (style == null) {
    throw NoSuchStyle;
  } else {
    return style;
  }
}

function extractStyles(styleGetters, styles) {
  return $$Array.of_list(List.map((function (styleGetter) {
                    return extractNullableStyle(Curry._1(styleGetter, styles));
                  }), styleGetters));
}

exports.NoSuchStyle = NoSuchStyle;
exports.composeStyles = composeStyles;
exports.extractNullableStyle = extractNullableStyle;
exports.extractStyles = extractStyles;
/* No side effect */
