// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var GlobalCss = require("./Global.css");
var App$ReactHooksTemplate = require("./App.bs.js");

var globalStyles = GlobalCss;

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

exports.globalStyles = globalStyles;
/* globalStyles Not a pure module */
