// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("emotion");

function app(theme) {
  return Emotion.css("\n    border: 1px solid black;\n    color: " + (String(theme) + ".mainColor);\n  "));
}

exports.app = app;
/* emotion Not a pure module */
