// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var url = "https://jsonplaceholder.typicode.com/posts/";

function postToJs(param) {
  return {
          userId: param[/* userId */0],
          title: param[/* title */1],
          body: param[/* body */2]
        };
}

function postFromJs(param) {
  return /* record */[
          /* userId */param.userId,
          /* title */param.title,
          /* body */param.body
        ];
}

function post(post$1) {
  return /* record */[
          /* userId */Json_decode.field("userId", Json_decode.$$int, post$1),
          /* title */Json_decode.field("title", Json_decode.string, post$1),
          /* body */Json_decode.field("body", Json_decode.string, post$1)
        ];
}

var Decode = /* module */[/* post */post];

function fetchPost(postId) {
  return fetch(url + String(postId)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                var post$1 = post(json);
                return Promise.resolve(post$1);
              }));
}

fetchPost(3).then((function (param) {
        if (param !== undefined) {
          return Promise.resolve((console.log(postToJs(param)), /* () */0));
        } else {
          return Promise.resolve((console.log("null"), /* () */0));
        }
      }));

exports.url = url;
exports.postToJs = postToJs;
exports.postFromJs = postFromJs;
exports.Decode = Decode;
exports.fetchPost = fetchPost;
/*  Not a pure module */
