// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function str(prim) {
  return prim;
}

function floatMultiplied($$float) {
  return $$float * 10000000.00;
}

function intDivided($$int) {
  return $$int / 10000000 | 0;
}

function randomFloat(param) {
  return (Math.random() * 10000000.00 | 0) / 10000000 | 0;
}

function App(Props) {
  var match = React.useState((function () {
          return /* record */[/* number */0.0];
        }));
  var setState = match[1];
  var numberToDisplay = Pervasives.string_of_float(match[0][/* number */0]);
  return React.createElement("div", undefined, React.createElement("div", undefined, numberToDisplay), React.createElement("button", {
                  onClick: (function (e) {
                      return Curry._1(setState, (function (param) {
                                    return /* record */[/* number */Math.random()];
                                  }));
                    })
                }, "Random number, please"));
}

var make = App;

exports.str = str;
exports.floatMultiplied = floatMultiplied;
exports.intDivided = intDivided;
exports.randomFloat = randomFloat;
exports.make = make;
/* react Not a pure module */
