// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function App(Props) {
  var match = React.useReducer((function (param, action) {
          return /* record */[/* number */Math.random()];
        }), /* record */[/* number */0.0]);
  var dispatch = match[1];
  var numberToDisplay = match[0][/* number */0].toString();
  return React.createElement("div", undefined, React.createElement("div", undefined, numberToDisplay), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* GetRandom */0);
                    })
                }, "Random number, please"));
}

var make = App;

exports.str = str;
exports.make = make;
/* react Not a pure module */
