// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var External = require("./External");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

function longest(str1, str2) {
  var combinedStr = str1 + str2;
  return combinedStr.split("").reduce((function (acc, $$char) {
                    var match = acc.includes($$char);
                    if (match) {
                      return acc;
                    } else {
                      return acc.concat(/* array */[$$char]);
                    }
                  }), /* array */[]).sort().join("");
}

var answeredQuestions = /* array */[
  /* record */[
    /* number */1,
    /* state : Wrong */[/* Very */2],
    /* category : Math */0
  ],
  /* record */[
    /* number */2,
    /* state : Wrong */[/* Kinda */1],
    /* category : Science */1
  ],
  /* record */[
    /* number */3,
    /* state : Correct */0,
    /* category : Math */0
  ]
];

console.log("[Reason]: Process answers");

console.log(answeredQuestions.filter((function (param) {
              if (param[/* state */1] && param[/* category */2]) {
                return true;
              } else {
                return false;
              }
            })).map((function (q) {
            return q[/* number */0];
          })));

var jsMapperConstantArray = /* array */[
  /* tuple */[
    627136509,
    "ELECTRIC"
  ],
  /* tuple */[
    781516758,
    "FIRE"
  ]
];

function pokemonTypesToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function pokemonTypesFromJs(param) {
  return Js_mapperRt.revSearchAssert(2, jsMapperConstantArray, param);
}

function pokemonToJs(param) {
  return {
          name: param[/* name */0],
          type: param[/* _type */1],
          level: param[/* level */2]
        };
}

function pokemonFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* _type */param.type,
          /* level */param.level
        ];
}

var pokemonData = External.pokemon;

function bringInPokemonFromJs(jsPokemon) {
  return jsPokemon.map((function (pokemon) {
                return /* record */[
                        /* name */pokemon.name,
                        /* _type */pokemonTypesFromJs(pokemon.type),
                        /* level */pokemon.level
                      ];
              }));
}

function formatPokemonForJs(rePokemon) {
  return rePokemon.map((function (pokemon) {
                return {
                        name: pokemon[/* name */0],
                        type: pokemonTypesToJs(pokemon[/* _type */1]),
                        level: pokemon[/* level */2]
                      };
              }));
}

var pokemonDataTyped = bringInPokemonFromJs(pokemonData);

console.log("[Reason]: Process Pokemon");

console.log(formatPokemonForJs(pokemonDataTyped.filter((function (param) {
                if (param[/* _type */1] !== 627136509) {
                  return false;
                } else {
                  return param[/* level */2] > 70;
                }
              }))));

function str(prim) {
  return prim;
}

function filter(prim, prim$1) {
  return prim$1.filter(Curry.__1(prim));
}

function map(prim, prim$1) {
  return prim$1.map(Curry.__1(prim));
}

function Main$App(Props) {
  var pokemon = Props.pokemon;
  var prim = pokemon.filter((function (param) {
          var level = param[/* level */2];
          if (level > 70) {
            return true;
          } else {
            return level < 10;
          }
        }));
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Reason React"), prim.map((function (p) {
                    return React.createElement("div", {
                                key: p[/* name */0]
                              }, p[/* name */0]);
                  })));
}

var App = /* module */[/* make */Main$App];

ReactDOMRe.renderToElementWithId(React.createElement(Main$App, {
          pokemon: pokemonDataTyped
        }), "reason-app");

var myExternalJs = /* () */0;

exports.myExternalJs = myExternalJs;
exports.longest = longest;
exports.answeredQuestions = answeredQuestions;
exports.pokemonTypesToJs = pokemonTypesToJs;
exports.pokemonTypesFromJs = pokemonTypesFromJs;
exports.pokemonToJs = pokemonToJs;
exports.pokemonFromJs = pokemonFromJs;
exports.pokemonData = pokemonData;
exports.bringInPokemonFromJs = bringInPokemonFromJs;
exports.formatPokemonForJs = formatPokemonForJs;
exports.pokemonDataTyped = pokemonDataTyped;
exports.str = str;
exports.filter = filter;
exports.map = map;
exports.App = App;
/*  Not a pure module */
