// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function yo(str) {
  return $$String.concat(str, /* :: */[
              "Hey",
              /* :: */[
                "Hi",
                /* [] */0
              ]
            ]);
}

exports.yo = yo;
/* No side effect */
