// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Modules$Day2 = require("./Modules.bs.js");

console.log(Modules$Day2.$$Math[/* square */1](3));

console.log(Modules$Day2.$$Math[/* coolGreeting */2]("dude"));

/*  Not a pure module */
