// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Hi$Day2 = require("./Hi.bs.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Arrays$Day2 = require("./Arrays.bs.js");

var ArraysToolbox = /* module */[/* checkPangram */Arrays$Day2.isPangram];

console.log(Arrays$Day2.isPangram("The quick brown fox jumps over the lazy dog"));

var coolGreeting = Hi$Day2.yo;

var times = Caml_int32.imul;

function square(x) {
  return Caml_int32.imul(x, x);
}

var $$Math = /* module */[
  /* times */times,
  /* square */square,
  /* coolGreeting */coolGreeting
];

exports.ArraysToolbox = ArraysToolbox;
exports.$$Math = $$Math;
/*  Not a pure module */
