// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Modules$Day2 = require("./Modules.bs.js");

console.log(Modules$Day2.$$Math[/* square */1](2));

/*  Not a pure module */
