// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Arrays$Day2 = require("./Arrays.bs.js");

var ArraysToolbox = /* module */[/* checkPangram */Arrays$Day2.isPangram];

console.log(Arrays$Day2.isPangram("The quick brown fox jumps over the lazy dog"));

function times(x, y) {
  return Caml_int32.imul(y, y);
}

function square(x) {
  return Caml_int32.imul(x, x);
}

var Tools = /* module */[
  /* times */times,
  /* square */square
];

var $$Math = /* module */[/* Tools */Tools];

console.log(9);

exports.ArraysToolbox = ArraysToolbox;
exports.$$Math = $$Math;
/*  Not a pure module */
