// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function onChange(watchHandler, watcher) {
  watcher.on("change", watchHandler);
  return /* () */0;
}

exports.onChange = onChange;
/* No side effect */
