// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Chokidar = require("chokidar");

function makeWatcher(pattern) {
  return Chokidar.watch(pattern);
}

function onChange(watchHandler, watcher) {
  watcher.on("change", watchHandler);
  return /* () */0;
}

exports.makeWatcher = makeWatcher;
exports.onChange = onChange;
/* chokidar Not a pure module */
