// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("css");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Knode$Cxb = require("./Knode.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Minimist$Cxb = require("./Minimist.bs.js");

var alias = {
  p: "path",
  h: "help"
};

var $$default = {
  path: ".",
  help: false
};

var string = /* array */["path"];

var $$boolean = /* array */["help"];

function unknown(err) {
  console.log(err);
  return /* () */0;
}

var Minimist = Minimist$Cxb.Make(/* module */[
      /* alias */alias,
      /* default */$$default,
      /* string */string,
      /* boolean */$$boolean,
      /* unknown */unknown
    ]);

console.log(Curry._1(Minimist[/* parse */0], /* array */[
          "--path",
          "dude"
        ]));

var myCss = Css.parse(Knode$Cxb.Fs[/* readFileSync */1]("test.css", "utf8"));

console.log($$Array.map((function (rule) {
            return Caml_array.caml_array_get(rule.selectors, 0);
          }), myCss.stylesheet.rules));

exports.Minimist = Minimist;
exports.myCss = myCss;
/* Minimist Not a pure module */
