// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("css");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Knode$Cxb = require("./Knode.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Minimist$Cxb = require("./Minimist.bs.js");

var alias = {
  p: "path",
  h: "help"
};

var $$default = {
  path: ".",
  help: false
};

var Minimist = Minimist$Cxb.Make(/* module */[
      /* alias */alias,
      /* default */$$default
    ]);

var options = Curry._3(Minimist[/* makeOptions */0], "path", "help", (function (err) {
        console.log(err);
        return /* () */0;
      }));

console.log(Curry._2(Minimist[/* parse */1], options, /* array */[
          "--path",
          "dude"
        ]));

var myCss = Css.parse(Knode$Cxb.Fs[/* readFileSync */1]("test.css", "utf8"));

console.log($$Array.map((function (rule) {
            return Caml_array.caml_array_get(rule.selectors, 0);
          }), myCss.stylesheet.rules));

exports.Minimist = Minimist;
exports.options = options;
exports.myCss = myCss;
/* Minimist Not a pure module */
