// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Fs = /* module */[];

var Path = /* module */[];

var Process = /* module */[];

exports.Fs = Fs;
exports.Path = Path;
exports.Process = Process;
/* No side effect */
