// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function existsSync(path) {
  return Fs.existsSync(path);
}

function readFileSync(path, encoding) {
  return Fs.readFileSync(path, encoding);
}

function writeFileSync(path, content, encoding, errorHandler) {
  Fs.writeFileSync(path, content, encoding, errorHandler);
  return /* () */0;
}

var Fs$1 = /* module */[
  /* existsSync */existsSync,
  /* readFileSync */readFileSync,
  /* writeFileSync */writeFileSync
];

var Path = /* module */[];

var Process = /* module */[];

exports.Fs = Fs$1;
exports.Path = Path;
exports.Process = Process;
/* fs Not a pure module */
