// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Minimist = require("minimist");

function Make(Config) {
  var parse = function (input) {
    return Minimist(input, {
                string: Config[/* string */2],
                boolean: Config[/* boolean */3],
                alias: Config[/* alias */0],
                default: Config[/* default */1],
                unknown: Config[/* unknown */4]
              });
  };
  return /* module */[/* parse */parse];
}

exports.Make = Make;
/* minimist Not a pure module */
