// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

function b(a, b$1) {
  return a + b$1 | 0;
}

var whoami = /* record */[
  /* name */"kal",
  /* age */30
];

exports.b = b;
exports.whoami = whoami;
/*  Not a pure module */
