// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


function received(thing) {
  return String(thing) + "1";
}

function print(log) {
  console.log("print " + String(log));
  return /* () */0;
}

exports.received = received;
exports.print = print;
/* No side effect */
