// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Log$Day3 = require("./Log.bs.js");

function greatReceived(i) {
  return Log$Day3.received(i) + "100";
}

var LogWith100 = /* module */[
  /* received */Log$Day3.received,
  /* print */Log$Day3.print,
  /* greatReceived */greatReceived
];

exports.LogWith100 = LogWith100;
/* No side effect */
