// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Log$Day3 = require("./Log.bs.js");
var LogWithSomething$Day3 = require("./LogWithSomething.bs.js");

console.log(Log$Day3.received(1));

console.log(LogWithSomething$Day3.LogWith100[/* greatReceived */2](2));

Log$Day3.print(32);

var L = 0;

exports.L = L;
/*  Not a pure module */
