// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var FunctorExample$Day3 = require("./FunctorExample.bs.js");

var Count = /* module */[/* count */4];

var Repeat = FunctorExample$Day3.Make(Count);

console.log(Curry._2(Repeat[/* repeat */0], undefined, "abc\n"));

exports.Count = Count;
exports.Repeat = Repeat;
/* Repeat Not a pure module */
