// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pg = require("pg");

function makeClient(connectionString) {
  return new Pg.Client(connectionString);
}

exports.makeClient = makeClient;
/* pg Not a pure module */
