// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MexicanRestaurant$ReactHooksTemplate = require("./MexicanRestaurant.bs.js");

function str(prim) {
  return prim;
}

function App(Props) {
  var match = React.useReducer((function (param, action) {
          return /* record */[/* restaurants : array */[null]];
        }), /* record */[/* restaurants : array */[React.createElement(MexicanRestaurant$ReactHooksTemplate.make, {
                key: "0"
              })]]);
  return React.createElement("div", undefined, match[0][/* restaurants */0]);
}

var make = App;

exports.str = str;
exports.make = make;
/* react Not a pure module */
